

#[dependencies]

[[dependencies.hexl]]
name = "1.2.1"
tool = "cmake"
fetch = "git"
#fetch = "git clone git@github.com:intel/hexl.git --branch %name%"
decompress = "tar xvf"
src_dir = ""
build_dir = ""
install_dir = ""
pre-build = "-S %src_dir% -B %build_dir% -DENABLE_DEBUG=ON"
build = "--build %build_dir% -j"
install = "--install %install_dir%"


#downloads /-
#build/-
#     |-1.2.1
#        |-HEKIT_SUCCESS
#
#[[hexl]]
#
#
#[[hexl]]
#
#
#[libraries]
#
#[[seal]]
#name
#
