[[dependency.hexl]]
skip = true
name = "1.2.1"
fetch = "git clone https://github.com/intel/hexl.git --branch %name%"
fetch_dir = "~/.hekit/hexl/1.2.1/fetch"
build_dir = "~/.hekit/hexl/1.2.1/build"
install_dir = "~/.hekit/hexl/1.2.1/install"
pre-build = """ cmake -S %fetch_dir%/hexl -B %build_dir%
               -DCMAKE_INSTALL_PREFIX=%install_dir%"""
build = "cmake --build %build_dir% -j"
install = "cmake --install %install_dir%"


[[dependency.hexl]]
skip = true
name = "1.2.0"
fetch = "git clone https://github.com/intel/hexl.git --branch 1.2.1"
src_dir = ""
build_dir = ""
install_dir = ""
pre-build = "-S %src_dir% -B %build_dir% -DENABLE_DEBUG=ON"
build = "--build %build_dir% -j"
install = "--install %install_dir%"


[[dependency.dummy]]
name = "a"
fetch = ""
fetch_dir = "~/.hekit/dummy/a/fetch"
build_dir = "~/.hekit/dummy/a/build"
install_dir = "~/.hekit/dummy/a/install"
pre-build = ""
build = ""
install = ""
