[[dependency.hexl]]
skip = false
name = "1.2.1"
fetch = "git clone https://github.com/intel/hexl.git --branch %name%"
init_fetch_dir = "~/.hekit/hexl/1.2.1/fetch"
init_build_dir = "~/.hekit/hexl/1.2.1/build"
init_install_dir = "%init_build_dir%"
pre-build = """cmake -S %init_fetch_dir%/hexl -B %init_build_dir%
               -DCMAKE_INSTALL_PREFIX=%export_install_dir%"""
build = "cmake --build %init_build_dir% -j"
post-build = ""
install = "cmake --install %init_install_dir%"
export_install_dir = "~/.hekit/hexl/1.2.1/install"


[[dependency.ntl]]
skip = true
version = "11.5.1"
name = "%version%"
fetch_dir = "~/.hekit/ntl/%version%/fetch"
build_dir_pre = "~/.hekit/ntl/%version%/build"
build_dir = "~/.hekit/ntl/%version%/build/ntl-%version%/src"
install_dir = "~/.hekit/ntl/%version%/install"
fetch = "wget https://libntl.org/ntl-%version%.tar.gz"
# At mo, some progs can't expand tilde
pre-build = "bash -c 'tar -xvf %fetch_dir%/ntl-%version%.tar.gz -C %build_dir_pre%'"
build = "bash -c './configure PREFIX=%install_dir% && make -j'"
install = "make install"


[[library.seal]]
skip = true


[[library.dummy]]
skip = false
dependecies = ["hexl/1.2.1", "ntl/11-debug"]
system_dependencies = [ "libgmp" ]


[[dependency.dummy]]
skip = true
name = "a"
fetch = ""
fetch_dir = "~/.hekit/dummy/a/fetch"
build_dir = "~/.hekit/dummy/a/build"
install_dir = "~/.hekit/dummy/a/install"
pre-build = ""
build = ""
install = ""
